### ISSUE TITLE
Fleet uninstall / disable docs

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet-docs#124]
https://fleet.rancher.io/uninstall doesn't explain that it only applies to standalone Fleet.

We should improve documentation here and add some explanation how to disable Fleet in Rancher, esp. what deactivating the `continuous-delivery` feature flag means in detail.

**Comment by sbulage** [comment]
Hello @kkaempf 

I came across these documentation available on _**SUSE Rancher Documentation**_ (below) which covers the _**Continuous Delivery**_ option in _**Rancher**_.

* https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/experimental-features/continuous-delivery.html
* https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/experimental-features/experimental-features.html#_enabling_features_with_the_rancher_ui

Above links are also available under _**Rancher Manager Community**_ documentation.

* https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/enable-experimental-features/continuous-delivery
* https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/enable-experimental-features#enabling-features-with-the-rancher-ui

<details>
<summary>Screenshot showing <b><i>Continuous Delivery</i></b> option under <b><i>Global Settings</i></b>.</summary>

![Screenshot from 2024-10-23 21-45-58](https://github.com/user-attachments/assets/3feceaf6-b6b7-4354-a8ee-f5c066221ce9)

</details>

All above documentation mentioning about Disabling Continuous Delivery option on Rancher.

Let us know here if you want further more information or documentation updation.
