### ISSUE TITLE
Document Helm chart values

### ISSUE THREAD

**Issue by moio** [rancher/fleet-docs#15]
At this point no documentation exists about [Helm chart parameter values](https://github.com/rancher/fleet/blob/master/charts/fleet/values.yaml). 

Most of them are for rather special/advanced uses, but ideally a full reference should be provided - see as an inspiration [Rancher’s Helm Chart Options page](https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/installation-references/helm-chart-options))

**Comment by manno** [comment]
Hey, do you know how that page was created?

For now I added https://fleet.rancher.io/next/ref-configuration#helm-charts

**Comment by moio** [comment]
No, sorry, I tried to do some digging but couldn't make sense of what happened pre-Docusaurus. Maybe #discuss-rancher-docs can help

**Comment by manno** [comment]
The upcoming docs link to the values files now: https://fleet.rancher.io/next/ref-configuration#helm-charts

**Comment by manno** [comment]
It looks like Rancher does that manually. For now the documentation in the values.yaml  should be sufficient.
