### ISSUE TITLE
fleet.rancher.io doesn't serve a 3xx on http requests

### ISSUE THREAD

**Issue by junkiebev** [rancher/fleet-docs#39]
Not really a bug, but a possible misconfiguration I figured you might care about: Requests to http://fleet.rancher.io are answered directly instead of being 302'd (or whatever) to https

![image](https://user-images.githubusercontent.com/6684332/131603788-9560d842-9cd3-4068-bc03-07efecf5dbd6.png)

**Comment by kkaempf** [comment]
Fixed meanwhile
