### ISSUE TITLE
Restructure docs (fleet.rancher.io)

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet-docs#44]
The current docs are more like a reference and don't follow our guidelines.
E.g.: https://fleet.rancher.io/gitrepo-add

- [ ] import examples into documentation
- [ ] tabs for examples
- [ ] full examples in github repo
- [ ] content should be by application, e.g. create a gitrepo for multicluster (tabs again)
- [ ] going by sections (much like k8s docs)
- [ ] list all/lesser used options at the end of a page
- [ ] user guide (recipes) vs tutorials (story)
- [ ] better reference section
- [ ] helm options
- [ ] get rid of fleet-examples? (fleet-examples tests vs. tests using fleet-examples)

**Comment by manno** [comment]
Closing for now. 

These pages will be split in a follow up PR:

* https://fleet.rancher.io/gitrepo-add
* https://fleet.rancher.io/gitrepo-structure
