### ISSUE TITLE
Fix quickstart download URLS

### ISSUE THREAD

**Issue by mattfarina** [rancher/fleet-docs#5]
In the quickstart the second code section has ...

```
helm -n cattle-fleet-system install --create-namespace --wait \
    fleet-crd https://github.com/rancher/fleet/releases/download/{{fleet.version}}/fleet-crd-{{fleet.version}}.tgz
helm -n cattle-fleet-system install --create-namespace --wait \
    fleet https://github.com/rancher/fleet/releases/download/{{fleet.version}}/fleet-{{fleet.version}}.tgz
```

In these there is `{{fleet.version}}`. This should be replaced with a version number rather than a replacement string. This had been part of the mkdocs config (seen [here](https://github.com/rancher/fleet/blob/31a71a12c455328926e2f6fdcdd98ab8094590fd/mkdocs.yml#L58)). The generated docs previously could just be copy/paste. They cannot now. 

Found this while reviewing https://github.com/rancher/fleet/pull/1010

**Comment by olblak** [comment]
Shameless promotion, on Epinio website we use Updatecli to automation version update in doc website using Updatecli with this [manifest](https://github.com/epinio/docs/blob/main/updatecli/updatecli.d/installation.yaml)

But maybe Docusaurus has a way to define global variable like mkdoc used to have

**Comment by kkaempf** [comment]
This is fixed
