### ISSUE TITLE
GitRepo status fleet

### ISSUE THREAD

**Issue by martyav** [rancher/fleet-docs#60]
This issue was originally opened by @mrolmedo in the Rancher Manager docs (https://github.com/rancher/rancher-docs/issues/538)

> Hi there,
> Our documentation includes the different statuses regarding bundles and clusters fleet objects:
>
> Latest version: https://fleet.rancher.io/cluster-bundles-state
> 0.5 version: https://fleet.rancher.io/0.5/cluster-bundles-state
> 0.4 version: https://fleet.rancher.io/0.4/cluster-bundles-state
> Could we include or add the same kinf of information for GitRepo objects?
> 
> Thanks

**Comment by kkaempf** [comment]
closing as done
