### ISSUE TITLE
Link broken 

### ISSUE THREAD

**Issue by mrolmedo** [rancher/fleet-docs#64]
Hi there,
There is a broken link in https://rancher.support/training/fleet/fleet-training-guide/#how-does-fleet-work section. The link  https://fleet.rancher.io/examples/ redirects to " Page Not Found".

**Comment by kkaempf** [comment]
Thanks for reporting !

There are multiple problems in the `rancher.support` web site. 🙈

**Comment by mrolmedo** [comment]
@kkaempf No worries, I´m part of the team. I will report anytime I see any issue to have the best docs.

**Comment by kkaempf** [comment]
The link should go to [Bundle Lifecycle](https://fleet.rancher.io/ref-bundle-stages)

**Comment by kkaempf** [comment]
fix got merged

**Comment by mrolmedo** [comment]
@kkaempf I found another link broken, do you prefer me to open a new PR or use the same one?

**Comment by kkaempf** [comment]
I'd prefer a new pr, thanks !
